/*++

Module Name:

	public.h

Abstract:

	This module contains the common declarations shared by driver
	and user applications.

Environment:

	user and kernel

--*/

//
// Define an Interface Guid so that apps can find the device and talk to it.
//
#pragma once

DEFINE_GUID(GUID_DEVINTERFACE_VIRTUALHID, 0x8658c58a, 0x8fc2, 0x4959, 0xa6, 0x81, 0x8b, 0x96, 0xf2, 0xf7, 0x41, 0x07);
//8658c58a - 8fc2 - 4959 - a681 - 8b96f2f74107


#define  VHID_RAW_DEVICE_ID		L"{8658C58A-8FC2-4959-A681-8b96F2F74107}\\vHidRawPdo\0"
#define  VHID_HARDWARE_ID		L"{8658C58A-8FC2-4959-A681-8b96F2F74107}\\vHidRawPdoHw\0"
#define  VHID_DEVICE_TEXT_409	L"vHid Driver"
#define  VJOY_DEVICE_INSTANCE	L"vHidInstance%02d"

#define F_GET_FEATURE							0x910
#define F_SET_FEATURE							0x911
#define F_READ_REPORT							0x912
#define F_WRITE_REPORT							0x913
#define F_GET_INPUT_REPORT						0x914
#define F_SET_OUTPUT_REPORT						0x915
#define F_COMPLETE_GET_FEATURE					0x916
#define F_COMPLETE_READ_REPORT					0x917
#define F_COMPLETE_GET_INPUT_REPORT				0x918
#define F_TEST_WRITE							0x919
#define F_TEST_READ								0x920

// IO Device Control codes;
#define GET_FEATURE					CTL_CODE (FILE_DEVICE_UNKNOWN, F_GET_FEATURE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SET_FEATURE				    CTL_CODE (FILE_DEVICE_UNKNOWN, F_SET_FEATURE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define COMPLETE_GET_FEATURE		CTL_CODE (FILE_DEVICE_UNKNOWN, F_COMPLETE_GET_FEATURE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define READ_REPORT		            CTL_CODE (FILE_DEVICE_UNKNOWN, F_READ_REPORT, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define WRITE_REPORT		        CTL_CODE (FILE_DEVICE_UNKNOWN, F_WRITE_REPORT, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define COMPLETE_READ_REPORT		CTL_CODE (FILE_DEVICE_UNKNOWN, F_COMPLETE_READ_REPORT, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GET_INPUT_REPORT            CTL_CODE (FILE_DEVICE_UNKNOWN, F_GET_INPUT_REPORT, METHOD_NEITHER, FILE_ANY_ACCESS)
#define SET_OUTPUT_REPORT           CTL_CODE (FILE_DEVICE_UNKNOWN, F_SET_OUTPUT_REPORT, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define COMPLETE_GET_INPUT_REPORT	CTL_CODE (FILE_DEVICE_UNKNOWN, F_COMPLETE_GET_INPUT_REPORT, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TEST_WRITE					CTL_CODE (FILE_DEVICE_UNKNOWN, F_TEST_WRITE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define TEST_READ					CTL_CODE (FILE_DEVICE_UNKNOWN, F_TEST_READ, METHOD_BUFFERED, FILE_ANY_ACCESS)

